name: xesn
channels:
    - conda-forge
dependencies:
    - python=3.11
# Basics
    - numpy
    - scipy
    - matplotlib
# xarray et al
    - xarray
    - netCDF4
    - bottleneck
    - dask[complete]
    - zarr
# surrogate modeling toolbox
    - smt>=2.2.1
# jupyter etc
    - jupyter
# Testing
    - pytest
    - coverage
# docs stuff
    - seaborn
    - nbsphinx
    - sphinx-book-theme
    - sphinxcontrib-bibtex
# GPUs
# uncomment the following lines
#    - cupy
#    - cupy-xarray
